---
name: Alien-SVN
version: 1.4.5.0
author: []
abstract: A wrapper for installing the SVN Perl bindings
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.8.0
build_requires:
  ExtUtils::MakeMaker: 6.31
provides:
  Alien::SVN:
    file: lib/Alien/SVN.pm
    version: 1.4.5.0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
